- .travis.yml
- README.rst
- travis.sh
There might a case where you don't want to run the tests, neither from build nor install spaces.
Example; device driver packages where emulation is not yet available, but you still want to check other things defined in the CI config (build etc.)
Since `NOT_TEST_INSTALL` is already implemented, in this PR I'm adding `NOT_TEST_BUILD`.
> Add option to not test 

- travis.sh
As per title.
Looking at [travis/build/shell/dsl.rb](https://github.com/travis-ci/travis-build/blob/91bf066/lib/travis/build/shell/dsl.rb#L58-L63) it's `travis_*`, not `traivs_*`.
> Fix folding typo (traivs->travis).

- travis.sh
to keep the code cleaner. Looks like the patch in `rostest` in question is already included in [deb version of 1.11.16 that's already out there](http://repositories.ros.org/status_page/ros_indigo_default.html?q=rostest).
This PR will resolve a patch error like https://github.com/ros-industrial/staubli/pull/20#issuecomment-18076221.
> Move a patch that becomes available via DEB to older ROS distro only section

- .travis.yml
- README.rst
- travis.sh
Fixing that some args for the number of parallel job are not documented nor set default values.
> Fix undeclared args for the number parallel job

- travis.sh
The `-q` and `-qq` switches must be appended before the apt-get command to work.
Providing `-q` and `-qq` is useless as `-qq` overrides `-q`.
man:
```
-q, --quiet
Quiet; produces output suitable for logging, omitting progress indicators. More q's will produce more quiet up to a maximum of 2. You can also use -q=# to set the quiet
level, overriding the configuration file. Note that quiet level 2 implies -y; you should never use -qq without a no-action modifier such as -d, --print-uris or -s as
APT may decide to do something you did not expect. Configuration Item: quiet.
```
> Fix apt-get quiet option

- travis.sh
Why is this the only thing that is not folded within the travis script? Doesn't seem very important to me
> Fold wstool version and localname info

- .travis.yml
- travis.sh
[How to acquire apt key has changed since Indigo](http://wiki.ros.org/indigo/Installation/Ubuntu#indigo.2BAC8-Installation.2BAC8-Sources.Set_up_your_keys). 
Not sure how relevant this is since the older method has been working so far for Indigo, but Travis today fails (e.g. [this](https://travis-ci.org/130s/moveit_core/jobs/128791932)) at key acquisition. So it's better to update to the latest method.
> Update ros.key acquision.

- README.rst
- Remove section `(Workaround) Prerelease Test job on Travis always passes`, which is already addressed in later commits in https://github.com/ros-industrial/industrial_ci/pull/35
- Correction, clarifications
@ipa-mdl Would mind taking a look?
> [Prerelease Test] Doc correction, clarification.

- .travis.yml
- Dockerfile
- travis.sh
ROS Kinetic can only be built in Ubuntu Wily and Xenial. Xenial isn't
supported by Travis, so instead we use a Xenial docker container and
do the build in there.
The travis.sh script automatically detects whether to use docker
based on the value of ROS_DISTRO. The only change that downstream
repositories will need to make to enable ROS kinetic builds in Xenial
is add docker to their travis .travis.yml file.
> Run Kinetic builds from a docker container

- .travis.yml
- README.rst
- post-process.sh
- pre-process.sh
To the question #14 I found that we actually don't need additional implementation. As added to the readme in this PR, we can simply call pre-processing script(s).
This PR also adds tests for the proposed concept; install a [`sl` command](http://unix.stackexchange.com/a/341/14968) in the pre-process, and calling it in the post-process is successful as you see [in this output](https://travis-ci.org/130s/industrial_ci/jobs/101186280#L3309) (because of Travis' time-elapsed view, the output looks broken but we can tell the program is installed).
Lastly, only as a reference, I've experimented another way to address #14; See https://github.com/130s/industrial_ci/pull/5 where `travis.sh` is modified to accept custom script if specified. I found it redundant and overkill.
> Add how to call pre-process script (addresses #14).

- travis.sh
Work around #53 
I can't find an official way for `apt-get update` command to continue when it encounter an unaccessible repository. This change may not seem intelligent, but looking at the tests it's been working fine.
@VictorLamoine would you want to take a look?
> [Workaround] "apt-get update" stops when there's an unaccessible repo

- .travis.yml
tl;dr URL for a .rosintall file is wrong so that the Travis always fail for now. This PR should fix it.
@gavanderhoorn could you review and merge if this LGT you? I have to go to bed :/
Detailed storyline (*warning*: boring):
- In https://github.com/ros-industrial/industrial_ci/pull/59 I added .rosintall files along with the logic that utilize them, and also wanted to check if the logic worked in the same PR.
- Initially I used the URL of .rosintall files on my forked repo so that Travis could find them.
- Once Travis passed, I swapped URL with [the one in `ros-industrial` organization](https://github.com/ros-industrial/industrial_ci/pull/59/commits/a68ddaba00a57eeaa020a68defc1c3373ef10faf#diff-354f30a63fb0907d4ad57269548329e3R27 ). And merge the PR without making sure the Travis passes …
> [Urgent] Fix wrong github raw content URL.

- README.rst
- travis.sh
Was missing from Docker command:
```
-e UPSTREAM_WORKSPACE \
-e ROSINSTALL_FILENAME \
```
Which was causing this Travis failure: https://travis-ci.org/ros-planning/moveit_core/jobs/142616513
Also:
- Was not specifying DOWNSTREAM_REPO_NAME within Docker, so multiple instances of the same target repo was being downloaded
- Better document how to use an external rosinstall file (located outside target repo)
- My editor autoremoved whitespace
> Fix rosinstall include bug for Docker/Kinetic

- .travis.yml
- README.rst
- travis.sh
Found that the current document might be confusing for users (at https://github.com/ros-industrial/staubli_experimental/pull/12).
`USE_DEB` variable was already there since when this package was initially introduced but recently it's gone deprecated https://github.com/ros-industrial/industrial_ci/pull/59, and having it unchanged while adding .rosinstall would collide.
@gavanderhoorn Would you find this change clear enough?
> Better handling a cornercase where USE_DEB=true and UPSTREAM_WORKSPACE=file

- README.rst
- industrial_ci/ci_main.sh
Although industrial_ci isn't targeted at ROS hydro, I still maintain a hydro branch of some repositories to support legacy projects. The hydro version of catkin_test_results has no --verbose option, which causes the test to fail when used on hydro.
This PR checks to see if the --verbose flag exists before using it.
This was tested on a hydro branch of swri_robotics/mapviz: [before (failing)](https://travis-ci.org/swri-robotics/mapviz/builds/156967693) and [after (passing)](https://travis-ci.org/swri-robotics/mapviz/builds/157317100).
> Only use catkin_test_results --verbose if it exists

- industrial_ci/ros_pre-release.sh
Without knowing, [`docker` install instruction](https://docs.docker.com/engine/installation/linux/ubuntulinux/) might have been updated to NOT use the user `ubuntu`. They [surely updated URL of the page](http://wiki.ros.org/action/info/regression_tests?action=diff&rev2=58&rev1=57).
This fixes issues like https://github.com/ros-industrial/ros_canopen/pull/193#issuecomment-254575036 (confirmed on my fork that with this change Travis passed https://github.com/130s/ros_canopen/pull/3).
> Fix usermod error on docker-based ROS Prerelease

- industrial_ci/ci_main.sh
`UPSTREAM_WORKSPACE` and `ROSINSTALL_FILENAME` was missing in `docker run` command. Using rosinstall files with kinetic is not possible without this.
> fix environment variables passed to docker container

- .travis.yml
- industrial_ci/ci_main.sh
- industrial_ci/ros_pre-release.sh
Since kinetic tests are run in docker and the prerelease test uses docker as well, this resulted in a docker-in-docker configuration that did not work.
First I tried to make docker-in-docker work with travis, but I had to modify the xenial container a lot because of non-root user issues.
The simpler solution was to not run the prerelease test within docker.
(ros-jade-catkin must be installed for `catkin_test_results` in kinetic test)
Before: https://travis-ci.org/ros-industrial/ros_canopen/builds/184098605
After: https://travis-ci.org/ros-industrial/ros_canopen/builds/184216135
> fix kinetic prelease test

- industrial_ci/rosdep-install.sh
This patch forces rosdep-install.sh to exit on errors.
Without -e the script exit code was taken from the manifest handling code.
(https://github.com/ros-industrial/universal_robot/pull/277#issuecomment-269709029)
> Abort rosdep-install.sh on error

- .ci.rosinstall.jade
- .travis.rosinstall
- .travis.yml
- industrial_ci/Dockerfile
This PR simplifies the test candidates to ultra stable packages with only few dependencies.
Test job duration will decrease from >1h to ~15 minutes.
Please note: The travis job for this PR will take about 20 minutes because job ~~15~~16 still uses the rosinstall file from the master branch.
> Speedup tests

- industrial_ci/package.xml
<s>See https://github.com/ros-industrial/industrial_ci/pull/101#issuecomment-272899368
I'm adding back `industrial_core` to a job that uses .rosinstall file on Kinetic. Rationale:
- Now that `industrial_core` is released into Kinetic. Kinetic will be maintained longer, and we want more Kinetic samples.
- It's allow_failure so that if in hurry we can<s>'t</s> still ignore this particular job.
</s>
Also added is the maintainer addition (picked from https://github.com/ros-industrial/industrial_ci/pull/86#issuecomment-268507950, which needs reconsideration and therefore on a hiatus now).
> Add maintainer

- industrial_ci/util.sh
Current master leads to doubled `after_script` fold closings because `TRAVIS_FOLD_NAME` is not unset properly.
> fix unset of TRAVIS_FOLD_NAME

- industrial_ci/source_tests.sh
Packages without share folder (e.g. metapackages) break the install tests.
This fix just ignores these errors.
Example: https://travis-ci.org/ipa-mdl/ros_canopen/jobs/193791905
> handle missing install/share/$pkg folders

- industrial_ci/src/tests/source_tests.sh
#114 removed ssh-client from the installed package as it is just a recommended package.
As a result #92 is not working anymore.
This is also addressed in #116
> [hotfix] install recommended ssh-client

- README.rst
Pointed out at https://github.com/ros-industrial/industrial_ci/pull/113#discussion_r97195126
> [doc] Correction; .ci_config is NO LONGER a required name.

- industrial_ci/src/tests/ros_prerelease.sh
This was the default before c1594f46900f40a00697b5669acb5d062ffbdaf0.
However, the generated scripts do not stop on errors: https://github.com/ros-infrastructure/ros_buildfarm/issues/367
> make prerelease test fail on test failures

- .travis.yml
travis-lint:
`specified compiler, but setting is not relevant for generic`
@ipa-bnm: FYI
> remove unused compiler settings

- doc/index.rst
[after_script in Travis CI](https://docs.travis-ci.com/user/customizing-the-build#Breaking-the-Build) doesn't affect the build result while the result in the commands specified with AFTER_SCRIPT in industrial_ci DOES affect the build result.
> [doc] Add notice for AFTER_SCRIPT, which behaves differently from after_script in Travis CI

- .travis.rosinstall
- industrial_ci/mockups/industrial_ci_testpkg/CMakeLists.txt
- industrial_ci/src/ci_main.sh
- industrial_ci/src/docker.sh
- industrial_ci/src/tests/source_tests.sh
- travis.sh
This is taken from #120.
I'd like to merge it separately as it is required for other development as well.
This commit prevents any directory changes within our scripts.
* does not assume the location to match a specific directoy
* prefix all commands (if needed)
* prefix all path
> use absolute paths

- doc/index.rst
I'm not entirely sure if stating the default value of `ROSINSTALL_FILENAME` as `.travis.rosinstall` -- this could give a wrong impression that this env var is always set (Fact is that it's only set/used when `UPSTREAM_WORKSPACE` is set as already explained.
But if one defines `UPSTREAM_WORKSPACE` but forgets `ROSINSTALL_FILENAME`, `.travis.rosinstall` will be sought for and if no file with that name found and the job fails. So I think it'd be still better to state default value.
> [doc] Clarify .rosinstall file usage.

- industrial_ci/src/docker.env
- industrial_ci/src/tests/source_tests.sh
Filters most of the rosdep install output, just prints commands and errors.
closes #141
> Silence rosdep

- .travis.yml
- industrial_ci/src/env.sh
This fixes a regression bug from #154 
It turned out that docker passes variabales as empty if it they have not been set on the host
This works for catkin and cmake, but might not work for custom/3rd-party Makefiles etc.
> unset empty CC and CXX variables

- .travis.yml
- industrial_ci/src/docker.sh
the docker image used for kinetic and lunar (ubuntu:xenial) does not have sudo installed
this triggers a failure in prepare_docker_image
> Install sudo in docker image

- ci.sh
- gitlab.sh
- industrial_ci/scripts/run_ci
as discussed in #157 
This introduces a generic `ci.sh` as suggested by @inigomartinez.
If `TARGET_REPO_PATH` and/or `TARGET_REPO_NAME` are not set, the current working directoy is used.
In contrast `travis.sh` does not use the working directory anymore, but reads the `TRAVIS*` variables instead.
> added generic ci.sh

- industrial_ci/src/tests/source_tests.sh
This PR picks some install space related commits from #137
The current master (still) builds all packages, cleans and rebuild to install space (unless `NOT_TEST_INSTALL=true).
These patches avoid rebuilding and fix the retry behavior.
> build directly to install space

- industrial_ci/src/docker.sh
Xenial docker image does not come with apt-utils installed, which leads to several warning messages:
`debconf: delaying package configuration, since apt-utils is not installed`
This also highly delays the creation of the docker container.
Second problem shows this error/warning message:
```
++ rosdep install -q --from-paths /root/catkin_ws --ignore-src --rosdistro kinetic -y
++ grep 'executing command'
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 132.)
debconf: falling back to frontend: Readline
```
> Handle problems with the xenial docker image

- industrial_ci/src/tests/ros_prerelease.sh
same fix as in https://github.com/ros-industrial/industrial_ci/pull/161, but for prerelease tests
Example: https://travis-ci.org/ros-industrial/industrial_ci/jobs/231828392
> [HOTFIX] fix missing sudo in prerelease tests

- industrial_ci/src/docker.sh
Installing the dependencies of the package using rosinstall might require to access a subversion repository. We copy the ~/.subversion folder to the docker container to copy the authorization when connecting directly to the subversion server (not through ssh).
> Pass subversion credentials from host to docker container.

- .gitlab-ci.yml
This PR fixes Gitlab CI.
It took me a while to understand, what's going on:
Gitlab's Docker-in-Docker service just shares specific folders with the build, at least everything below `/builds/$CI_PROJECT_NAMESPACE`.
Pipeline: https://gitlab.com/ipa-mdl/industrial_ci/pipelines/9499096
fixes #160
> Fix gitlab issues

- .travis.yml
<s>**DO NOT MERGE YET** - this should be mergeable once core packages of ROS Lunar become available (so maybe when https://github.com/ros/rosdistro/issues/13550 gets closed).</s> -> Condition cleared.
This addresses the concern raised at https://github.com/ros-industrial/industrial_ci/pull/131#issuecomment-281162743
> The [`lunar` job](https://travis-ci.org/ros-industrial/industrial_ci/jobs/203429152) passing already doesn't make sense to me, when there are only a couple of packages (I forgot what they were back then. Today more core packages have been already [released](http://repositories.ros.org/status_page/ros_lunar_default.html))?
Looking at the commit history at [rosdistro/lunar/distribution.yaml](https://github.com/ros/rosdistro/commits/master/lunar/distribution.yaml) the two …
> [ROS Lunar] Use mockups pkg as a smoke test.

- .travis.yml
- industrial_ci/_wrap_test.sh
This PR introduces a new feature for internal-use.
it can be used to run `industrial_ci` for external repositories, just as travis would do.
That's why I have introduced an internal script `_wrap_test.sh`.
@Jmeyer1292, @shaun-edwards, @gavanderhoorn, @ipa-fxm, @130s: Do you have some suggestions for other candidates?
In the end it should be a nice mix of ~5 external repos.
> test external projects again

- .travis.yml
- industrial_ci/src/docker.sh
- industrial_ci/src/env.sh
- industrial_ci/src/tests/ros_prerelease.sh
- industrial_ci/src/tests/source_tests.sh
Fixes #197 
This should only affect users that specify `DOCKER_BASE_IMAGE`.
For source tests the codename will be read with `lsb_release`.
For the prelease the codname has to be set explicitly, `OS_NAME` defaults to `ubuntu` for the sake of convenience.
@miguelprada: please test / review.
TODO;
> don't deduce OS names from DOCKER_BASE_IMAGE

- industrial_ci/src/tests/ros_prerelease.sh
Gitlab runners might have both available and the link must be used.
> prerelease test: prefer linked docker instance over socket interface

- doc/index.rst
- industrial_ci/src/tests/source_tests.sh
Not sure how effective this change is but trying to address confusion such as #212.
> [doc] Small elaboration for Docker image usage

- .gitlab-ci.yml
Prerelease tests for jade are not supported anymore, because it is EOL.
This patch fixes the example to work again.
https://gitlab.com/ipa-mdl/industrial_ci/pipelines/13297557
> do not run prerelease on gitlab for jade (EOL)

- .gitlab-ci.yml
It might break local builds if the overlay driver is not enabled in the kernel.
Instead a link to the Gitlab documentation was added.
closes #213
> remove overlay driver setting from gitlab example

- industrial_ci/src/tests/ros_prerelease.sh
Prerelease tests started to [fail](https://gitlab.com/ipa-mdl/industrial_ci/pipelines/14361205) on Gitlab because of TLS problems.
Updating to a recent docker version [resolves this](https://gitlab.com/ipa-mdl/industrial_ci/pipelines/14361018).
> install latest docker in prerelease container

- industrial_ci/src/docker.sh
Some jobs relying on my SSH credentials being copied into the docker container have started to fail. I believe this might be because the `~` character is not correctly expanded inside double quotes [here](https://github.com/ros-industrial/industrial_ci/blob/a0356c3a546d43a1bea819d7ffdb0f61ea849e7c/industrial_ci/src/docker.sh#L89), which were introduced in #240. Replacing with `$HOME` does the job for me.
> Replace ~ with $HOME for correct expansion.

- industrial_ci/src/tests/source_tests.sh
> Remove problematic `--no-deps` flag from `catkin_run_tests` command.

- .gitlab-ci.yml
- gitlab.sh
Automates the steps from the [gitlab docs](https://docs.gitlab.com/ee/ci/ssh_keys/README.html#ssh-keys-when-using-the-docker-executor).
`SSH_PRIVATE_KEY` and `SSH_SERVER_HOSTKEYS` have to be added as secret variables beforehand.
Instead of providing `SSH_SERVER_HOSTKEYS`,  StrictHostKeyChecking could be disabled via `.gitlab-ci.yml`, but this is not recommended.
This code ensures that it is only run in docker or in a disposable environemnt (only runners 10.1+).
@130s, @miguelprada: What do you think?
> setup ssh key forwarding in gitlab

- .gitlab-ci.yml
- industrial_ci/src/docker.sh
addresses #247 
Since docker 17.06 ownership of files copied into docker containers is kept instead of beeing rewritten to the target user. This PR emulates the old behavior until this bug was fixed in docker (WIP).
In addition this PR enables passing  credential files even for non-root images.
This patch might break again as soon as the docker bug is fixed.
@ipa-jba: please test
> set proper uid/gid for files copied to docker

- .travis.yml
- doc/index.rst
- industrial_ci/src/docker.sh
If `DOCKER_IMAGE` or `DOCKER_BASE_IMAGE` point to a different platform, then `INJECT_QEMU` can be set to  the appropriate version that should get injected automatically.
For example for ARM builds, `INJECT_QEMU=arm` has to be set.
Please note:
* For this to work the `qemu-user-static` package needs to be installed on the host (or the CI machine): `sudo apt-get install qemu-user-static`
* There is no need to inject QEMU if it is already present in the selected image
* The build is much slower, it is not suitable for regular CI checks. It might be better to test certain branches only or to provide an image with all dependencies (and QEMU).
includes #236, closes #235
> Inject QEMU for cross-platform build

- industrial_ci/src/tests/source_tests.sh
- Not run 'wstool init' when .rosinstall exists.
In a custom Docker image .rosinstall could exist. In that case `wstool init` returns code 1 and the entire job fails, which with this change can be avoided.
-  'rosdep install' only search src under . Addresses #257.
`src` folder is assumed in industrial_ci already (e.g. [here](https://github.com/ros-industrial/industrial_ci/blob/749d03f0fc9be6fb2779366ee165184c589362a4/industrial_ci/src/tests/source_tests.sh#L85)) so this change should make sense.
> A few improvement for potential issues with a custom Docker image

- industrial_ci/CMakeLists.txt
- industrial_ci/package.xml
- industrial_ci/scripts/run_travis
```
Usage: industrial_ci/scripts/run_travis [PATH] [RANGE*] [-- [ENV*]]
Parses the travis config in the given path or in the current working directory and runs all specified tests sequentially
If no range is given, the list of jobs will get printed.
The number of tests can be reduced by specifying one or more ranges:
* single job: 1 (only first)
* range: 2-3 (only second and third)
* open start, only as first range: -4 (jobs 1 to 4)
* open end, only as last range: 7- (job 7 and all following jobs)
* open range: - (all jobs)
Complex examples for a matrix wih 12 jobs:
* -4 7 8: runs jobs 1 2 3 4 7 8
* 1 7-9: runs jobs 1 7 8 9
* 1 7-9 11-: runs jobs 1 7 8 9 11 12
* -: runs all jobs
The jobs will be run in clean environments.
Only DOCKER_PORT, SSH_AUTH_SOCK, and TERM will be kept.
Additional …
```
> implemented run_travis

- industrial_ci/src/tests/source_tests.sh
This is my attempt to fix #253, as a replacement for #255 
It reverts #244, but sets `TARGET_PKGS` to all packages to address #232.
To make sure that all downstream packages and their dependencies get built, a dedicated step was added.
In addition `tests` will be built before `run_tests` to build the tests with the build options. 
@miguelprada: please test your bare rosinstall usecase
@ipa-fxm: please test with your setup
> Fix run_tests verbosity

- doc/index.rst
- industrial_ci/scripts/run_travis
I got an error. 
```
$ ~/industrial_ci/industrial_ci/scripts/run_travis .
File "/home/n130s/industrial_ci/industrial_ci/scripts/run_travis", line 3
SyntaxError: Non-ASCII character '\xc3' in file /home/n130s/industrial_ci/industrial_ci/scripts/run_travis on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
$
```
> [run_travis] Fix encoding error. Add a section in readme .

- industrial_ci/scripts/run_travis
> fix the error handling in run_travis

- .gitlab-ci.yml
- doc/index.rst
- industrial_ci/src/docker.sh
This PR adds a flag to disable automatic pull of images.
Setting it to false assumes that the (base) image was already pulled or provided otherwise.
Cherry-picked from #279 and extended to include `DOCKER_BASE_IMAGE`.
I will update #279 and #280 afterwards.
The test jobs are run on gitlab only: https://gitlab.com/ipa-mdl/industrial_ci/pipelines/23079479
> Add DOCKER_PULL option

- doc/index.rst
- industrial_ci/CMakeLists.txt
- industrial_ci/scripts/rerun_ci
- industrial_ci/src/docker.sh
- industrial_ci/src/tests/source_tests.sh
`rerun_ci` runs local tests like `run_ci`, but speeds up recurring builds by reusing the  image from the last run.
Each run will commit the container to `industrial-ci/run_ci/$REPO_NAME:$CLI_HASH`. The latter hashes the command line arguments. Thee will added to the images as a comment as well.
So each combination of (absolute) target path and enviromnent settings gets a dedicated image.
There are some differences between `run_ci` and `rerun_ci`:
* the first argument must be the target path, "." is okay as well.
* the images will persist, the users must delete them manually
* the environement gets filled only with the command line arguments
Please give it a try.
> [WIP] rerun_ci script

- .travis.yml
- travis.sh
This patch will print a line to the output after each 9 minutes of "silence" preventing Travis from stopping the build.
In contrast to `travis_wait` the output will not get printed at the end, but line-wise.
This might introduce a small performance penalty, because each output line is processed by bash,
but I guess this is neglectable.
Not sure if this feature needs an opt-in or opt-out..
> Travis timeout guard

- industrial_ci/src/tests/source_tests.sh
Bug in rosdep has been fixed (https://github.com/ros-infrastructure/rosdep/pull/612).
Should get merged after the next release.
> remove rosdep install output filter

- .travis.yml
- industrial_ci/scripts/run_travis
Small fixes for run_travis. Now `run_travis` can parse `industral_ci`'s .travis.yml again.
> run_travis fixes

- README.rst
The screenshot was taken over the holiday in a lot of countries but I do see the bottom number is still as high as the normal days from the previous years.
> Metrics update for 201812.

- industrial_ci/src/tests/source_tests.sh
- industrial_ci/src/util.sh
Addresses https://github.com/ros-infrastructure/rosdep/pull/647
The flag will only be set for EOL distros on systems which support this flag.
>  include EOL distros in rosdep update

- .travis.yml
Does not work anymore.
I guess because of https://github.com/ros/rosdistro/pull/20947, which seems not to be supported by the old version
> remove test with custom DOCKER_IMAGE

- travis.sh
possible fix for #364 
For Travis (=fresh VM per build job) this should be safe.
For Gitlab this might not be a good default.
> use host network for travis

- industrial_ci/src/tests/ros_prerelease.sh
Prerelease tests are currently broken, because the workspace has been renamed (https://github.com/ros-infrastructure/ros_buildfarm/pull/585).
Should get rebase-merged.
Afterwards, legacy should get pushed to master as well.
> renamed prerelease workspace to ws

- industrial_ci/src/env.sh
Reverts #378 partially, because the final snapshots have been [rolled back](https://discourse.ros.org/t/final-lunar-sync/9629/7).
> Revert switching to snapshots

- .travis.yml
indigo is not supported anymore (https://github.com/ros-infrastructure/ros_buildfarm_config/pull/137)
> run prerelease tests for melodic instead of indigo

- .travis.yml
https://docs.travis-ci.com/user/notifications/#default-notification-settings:
> By default, email notifications are sent to the committer and the commit author when they are members of the repository, that is they have
> - push or admin permissions for public repositories.
> - pull, push or admin permissions for private repositories.
> switch to default Travis notification settings

- industrial_ci/scripts/run_travis
fixes #409, should get backported to `legacy`.
@agutenkunst: please test
> pass PATH in run_travis

- README.rst
As per subject.
Not sure whether you'd rather have this in `master`, or whether you can 'port' this to that branch yourself.
> readme: repository was migrated to travis.com

- .travis.yml
- doc/index.rst
- industrial_ci/src/env.sh
[First sync is out](https://discourse.ros.org/t/ros-2-eloquent-elusor-call-for-testing-and-package-releases/10923).
Docker images are not available yet.
> support for ROS2 Eloquent Elusor

- industrial_ci/src/builders/colcon.sh
`ardent` needs the same fix as `kinetic`, since both are based on `xenial`.
> fix ROS2 ardent

- .travis.yml
- industrial_ci/scripts/run_travis
Moves `allow_failures` jobs to the end of the list, just as Travis does.
For industrial_ci:
```
Globals: POST_PROCESS='echo "post processing reached"' AFTER_SETUP_TARGET_WORKSPACE='echo current dir: $(pwd)'
Job  1: ROS_DISTRO=indigo TARGET_WORKSPACE='industrial_ci/mockups/industrial_ci_testpkg' VERBOSE_OUTPUT='true' CATKIN_LINT=true
Job  2: ROS_DISTRO=indigo TARGET_WORKSPACE='industrial_ci/mockups/industrial_ci_testpkg' CMAKE_ARGS="-DFAIL_CMAKE=true" EXPECT_EXIT_CODE=1
Job  3: ROS_DISTRO=indigo TARGET_WORKSPACE='industrial_ci/mockups/industrial_ci_testpkg' CATKIN_LINT=pedantic EXPECT_EXIT_CODE=1
Job  4: ROS_DISTRO=indigo TARGET_WORKSPACE='industrial_ci/mockups/industrial_ci_testpkg' ROSDEP_SKIP_KEYS="rospy_tutorials rostest" EXPECT_EXIT_CODE=1
Job  5: ROS_DISTRO=indigo …
```
> reorder allowed failures in run_travis

- .travis.yml
Workaound for MoveIt package missing from the testing repository for ROS `kinetic`.
(due to https://github.com/ros/rosdistro/pull/22798, more info: https://github.com/ros/rosdistro/pull/22797)
> test motoman_experimental against main ROS repository

- industrial_ci/src/workspace.sh
apparently `vcs import` has `--recursive` disabed by default
which is why github submodules are not pulled during setup_ws
from `vcs import --help`:
>  --recursive        Recurse into submodules (default: False)
I hope I covered all occurrences correctly...
> add --recursive for vcs import

- industrial_ci/src/env.sh
- industrial_ci/src/workspace.sh
Hi all, I created a way simpler and stupider version of ici for ROS 2 a while back ([ros2ci](https://github.com/mikaelarguedas/ros2ci/)). Main purpose was to be able to run CI on both released ROS 2 distros and ROS 2 nightly builds to catch breakage of packages against upcoming versions of ROS 2.
Now that ICI supports colcon + ROS 2 (hat tip @ipa-mdl :+1::tada:), I'd like to integrate the support for nightly builds instead of maintaining something on the side.
I'm opening this to start discussion of supporting nightly ROS 2 CI in ICI.
Feature description:
- run jobs based on OSRF's nightly ros2 docker images (Linux only)
- build a "middle-lay" with missing dependencies
- build and test packages on top of it
Is it a use case ICI would be interested in supporting?
---
Content of this PR:
- …
> Support for CI on top of ros2 nightly images

- .travis.yml
Fixed the currently broken ` legacy` build.
> freeze version of cob_calibration_data to stabilize tests

- industrial_ci/src/builders/catkin_tools.sh
quick fix as long as #458 is not ready
> initialize VERBOSE_OUTPUT and VERBOSE_TESTS to false

- industrial_ci/src/tests/source_tests.sh
regression on https://github.com/ros-industrial/industrial_ci/pull/369
Fixes
```
/root/ici/tests/source_tests.sh: line 246: error: command not found
```
> error was renamed to ici_error

- .travis.yml
test is unstable because of upstream changes
In the long run I want to remove most legacy tests to save build time.
> remove failing test of cob_calibration_data

- industrial_ci/src/workspace.sh
There is no working way to install `python-vcstool`. It is always `python3-vcstool`. This change affects only pre-noetic distros
> vcstool is always python3

- industrial_ci/src/env.sh
C++ compilier is missing
temporary fix for #515
> quickfix: do not use official Docker images by default

- industrial_ci/src/workspace.sh
This reverts commit 5a3936f0fe60ba42485d1cba8a51e231f8294b78.
Fixes #475 
ToDo:
> work-around for chained colcon workspaces with cmake-only packages

- industrial_ci/src/workspace.sh
This would enable me to change things in my .rosinstall files (like to point to a PR branch) without having to delete my docker image when I'm using `rerun_ci`.
> use --force option on vcs import

- industrial_ci/src/tests/abi_check.sh
to fix the abi checker install without #530
> set master branch for cloning the abi checker tools

- industrial_ci/src/workspace.sh
`HEAD` version is not a valid input for vcs anymore (https://github.com/dirk-thomas/vcstool/pull/147).
This fixes the ABI check failures.
> discard HEAD version in vcs import

- .github/workflows/main.yml
Signed-off-by: Chen Bainian <brian97cbn@gmail.com>
Add cron job for master branch only (default branch) every day on UTC 00:00.
Will rebase this once the shellcheck error is fixed.
> Github Action add cron for master branch

- travis.sh
Signed-off-by: Chen Bainian <brian97cbn@gmail.com>
Fix #542 
This problem has been bugging me for some time since the foxy-nightly docker
This fix will update libseccomp2 to higher than 2.3.3.
This will enable the docker-ce 18.06.0 run in Travis CI to allow statx syscall, which will fix the Qt5 RCC not found error in Foxy.
Reference: https://travis-ci.community/t/docker-build-environments/7216/4
> Update libseccomp2 to fix statx syscall error

- doc/index.rst
Note the workaround for my use-case of `rerun_ci`.  Related to https://github.com/ros-industrial/industrial_ci/pull/551
I'm sorry it took me so long to do this after you suggested it.  It looks like vim cleaned up some trailing whitespace in the document when I saved it.  If you'd like I can remove those changes from this pr.
> Add note about using vcs pull to return section

- README.rst
I created a mirror in @ipa320, which will run nightly builds on Travis CI.
> Point Travis CI badge to IPA mirror

- .gitlab-ci.yml
rosindustrial/ci:kinetic-xenial-shadow-fixed was removed
Passed: https://gitlab.com/ipa-mdl/industrial_ci/-/pipelines/249268377
> Fix docker_pull and docker_no_pull tests on Gitlab

- .gitlab-ci.yml
rosindustrial/ci:kinetic-xenial-shadow-fixed was removed
Passed: https://gitlab.com/ipa-mdl/industrial_ci/-/pipelines/249284727
> Remove docker pull tests on Gitlab

- industrial_ci/src/deprecated.sh
- industrial_ci/src/util.sh
Warns about renamed hooks and migratres the setting.
E.g., for prepare_docker_image -> pull_docker_image
> Implement ici_migrate_hook

- .github/action.sh
- .github/workflows/main.yml
- action.yml
```yaml
jobs:
industrial_ci:
strategy:
matrix:
ROS_DISTRO: [melodic]
ROS_REPO: [testing, main]
runs-on: ubuntu-latest
steps:
- ...
- uses: 'ros-industrial/industrial_ci@master'
with:
matrix: ${{toJSON(matrix)}}
```
`$` can be escaped with `$$`.
Without escaping, the variable substitution will happen immediately.
> Add matrix input to Github Action

- README.rst
Addressing #497 
- Change https://travis-ci.org to https://travis-ci.com for the bitbucket beta support;
- Address status badges' target link problem in the documentation.
> Edit doc to extend travis support to bitbucket beta

- doc/index.rst
- industrial_ci/src/env.sh
- industrial_ci/src/isolation/docker.sh
- industrial_ci/src/tests/black_check.sh
> Improve DOCKER_IMAGE detection

- industrial_ci/src/builders/catkin_tools.sh
ref https://github.com/ros-industrial/industrial_ci/issues/624#issuecomment-779354666
`BUILDER=catkin_tools` does not work for `noetic`:
```
Starting function 'build_upstream_workspace'
Traceback (most recent call last):
File "/usr/bin/catkin", line 6, in <module>
from pkg_resources import load_entry_point
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
def _initialize_master_working_set():
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
f(*args, **kwargs)
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master …
```
> also install osrf-pycommon for catkin_tools builder

- .gitlab-ci.yml
- industrial_ci/src/ci_main.sh
- industrial_ci/src/isolation/docker.sh
- industrial_ci/src/util.sh
As reported in https://github.com/ros-industrial/industrial_ci/pull/595#issuecomment-779171664
This paths creates the temporary folder, if BASEDIR is a sub-directory of TARGET_REPO_PATH or if they are equal.
Gitlab CI passed: https://gitlab.com/ipa-mdl/industrial_ci/-/pipelines/257815706
@stertingen: please have a look
> Always copy TARGET_REPO_PATH if it contains BASEDIR

- industrial_ci/scripts/run_ci
closes #642 
The issue with `--symlink-install` is that the files are linked individually, but the installed `src` folder actually exists.
This fix changes to real `src` first.
@tylerjw: please test
> Resolve all symbolic links before starting ci_main.sh from run_ci

- industrial_ci/mockups/failing_test/test/no_talker.test
- industrial_ci/mockups/industrial_ci_testpkg/test/example_ros.test
Simplify `.test` files listing ROS params as part of the `<test>` tag.
> unify test parameters

- .github/workflows/main.yml
- industrial_ci/mockups/industrial_ci_testpkg/CMakeLists.txt
- industrial_ci/mockups/industrial_ci_testpkg/src/test_compiler.cpp
I had a lot of trouble understanding, why my [rviz build didn't fail although I see compiler warnings](https://github.com/rhaschke/rviz/runs/2316648441) and have `-Werror` configured.
First I thought, `CXXFLAGS` are not correctly passed to the `BUILDER`. However, these tests prove that this works ok.
But, it looks like `CXXFLAGS` are not automatically passed to the child build job triggered for `python_qt_bindings` / `sip`.
Maybe, it's helpful to keep these tests anyway.
> unittest for passing of CXXFLAGS

- .github/workflows/legacy.yml
Why do you need a scheduled workflows at all? Each push is validated anyway. Scheduled workflows only make sense if you depend on external resources, so maybe `external.yml` but not main?
The core issue is of course is that [we cannot opt-in or opt-out to GHA on forks](https://github.community/t/stop-github-actions-running-on-a-fork/17965/4).
> Don't run (failing!) cron-job workflow on a fork

- .github/action.sh
> Make GitHub action fail gracefully if jq is not installed

- industrial_ci/src/tests/source_tests.sh
Fixup a bug introduced in #655: non-cpp files might get clang-tidy checked:
https://github.com/ros-planning/moveit_task_constructor/runs/2423567108
If no source files are found in `compile_commands.json`, the subsequent git filtering just returns *all* changed files. 
However these shouldn't be clang-tidy checked!
> run_clang_tidy: fix changed-files filter

- doc/index.rst
- industrial_ci/src/run.sh
This tests `UNDERLAY` to prevent from issues like #668.
The test was moved after the init script to allow for underlays created in a script.
Setting `UNDERLAY=/opt/ros/$ROS_DISTRO` will only work if a ROS-based Docker images is used.
@fmessmer, @tylerjw, @JStech : Please test
> Test that UNDERLAY contains a setup.bash

- .github/workflows/legacy.yml
The Ubuntu archive repository does not host the packages for precise anymore.
> Remove hydro test from legacy cron job

- industrial_ci/src/builders/catkin_tools.sh
- industrial_ci/src/builders/catkin_tools_isolated.sh
The resulting install space structure should be similar to colcon's.
This could be useful for detecting missing dependencies between packages.
Not sure, if we should provide an opt-out or if users should better fix their broken dependencies.
> Isolate install space with catkin_tools

- industrial_ci/src/builders/catkin_make_isolated_devel.sh
Same as #700, but for `catkin_make_isolated`.
Final test build is running: https://github.com/ubi-agni/moveit/runs/3081336989?check_suite_focus=true
> Add support for BUILDER=catkin_make_isolated_devel

- .github/workflows/main.yml
- industrial_ci/mockups/test_clang_tidy/.clang-tidy
- industrial_ci/src/tests/source_tests.sh
`clang-tidy` checks ignored existing `.clang-tidy` config files, because clang-tidy was run from `target_ws`.
Now instead, clang-tidy is run from the folder of each individual source file separately. A corresponding unit test is added. Additionally, I enabled hooks `BEFORE_CLANG_TIDY_CHECKS` and `AFTER_CLANG_TIDY_CHECKS`. These could be used to e.g. show the list of applied checks etc. They are applied _once_ before/after all clang-tidy checks in the `target_ws`.
> Fix clang-tidy checks

- .github/workflows/main.yml
- industrial_ci/CMakeLists.txt
- industrial_ci/package.xml
Fixes ROS2 pre-release of industrial_ci, does not fallback to catkin anymore.
> Require ROS_VERSION during build of industrial_ci

- industrial_ci/src/run.sh
> Do report missing setup.bash if UNDERLAY=/opt/ros/$ROS_DISTRO

- .github/workflows/main.yml
ubuntu-16.04 environment is deprecated (https://github.com/actions/virtual-environments/issues/3287)
> Remove isolated test job for kinetic

- .github/workflows/main.yml
- industrial_ci/src/ros.sh
While I would like to use colcon for ROS1 as well, it has several issues.
I hope that this will not break too many builds.
`BUILDER=colcon` is still supported, but now as an opt-in.
closes #629 and closes #666
@wxmerkt: Please test, if this resolves your build issues.
> Make catkin_tools the default builder for ROS1 noetic

- .github/workflows/main.yml
Fixes the (temporary) test failures.
> Test run_travis for ROS2 foxy instead of rolling

- industrial_ci/src/isolation/docker.sh
Docker is used with pseudo tty, which converts all newlines to CRLF
https://github.com/moby/moby/issues/8513#issuecomment-216191236
> Filter carriage returns from Docker output

- industrial_ci/src/workspace.sh
No need to create a temporary home directory for the default case
> Simplify gpg key import

- doc/index.rst
- industrial_ci/src/workspace.sh
Hello, 
I added this parsing command for url, if you just want to workspace extend with one private repo using ssh without creating a ".repos" or ".rosinstall" file (very niche case I guess).
Maybe there was already a way to achieve that but as I couldn't, I added this 'git+ssh'.
Does it make sense ?
Thank you !
> added special workspace setup for just one repo

- doc/index.rst
Branch name needs to be separated by `#` not `@`.
> Fix tiny typo in doc

- industrial_ci/src/builders/catkin_tools_devel.sh
I need to come back to https://github.com/ros-industrial/industrial_ci/pull/707/files#r673922264. Unfortunately, using a linked devel-space layout is not compatible with the `--install` flag: https://github.com/catkin/catkin_tools/issues/674#issuecomment-879008090.
Sourcing `devel/setup.bash` [doesn't yield the correct `ROS_PACKAGE_PATH`](https://github.com/ros-planning/moveit/runs/4130420882?check_suite_focus=true#step:5:315) (not including the sourced workspace), such that `find_package(catkin ...)` yields wrong results. Dropping the `--install` flag, everything [works as expected](https://github.com/ros-planning/moveit/runs/4130667967?check_suite_focus=true).
> catkin_tools_devel.sh: drop --install flag

- industrial_ci/src/tests/black_check.sh
> Do not set DOCKER_IMAGE in BLACK_CHECK, if ROS_DISTRO is set

- doc/industrial_ci_action.yml
closes #590 
Based on https://github.com/ros-industrial/fanuc/blob/melodic-devel/.github/workflows/ci_bionic.yml
> Update Github Actions template

- .github/workflows/main.yml
- doc/index.rst
- industrial_ci/src/ros.sh
We should add humble to the supported distros. 
I think this will do it but I still need to test.
> Add humble to the supported distros

- industrial_ci/src/builders/catkin_tools.sh
Calling `catkin build --catkin-make-args run_tests` is only correct for catkin packages, not for pure cmake packages, which require  `catkin build --catkin-make-args test`. `catkin test` selects the correct build target automatically:
https://catkin-tools.readthedocs.io/en/latest/verbs/catkin_test.html?highlight=run_tests#basic-usage
> catkin tools should call `catkin test` for testing

- industrial_ci/src/builders/colcon.sh
This adds support for VERBOSE_OUTPUT to colcon.
It enables output for stdout (`console_cohesion+`) which would otherwise only be written to a logfile and not accessible to debug in CI.
cc @fmessmer
> Support VERBOSE_OUTPUT for colcon

- .github/workflows/legacy.yml
- .github/workflows/main.yml
- README.rst
- doc/industrial_ci_action.yml
Fix warnings about deprecated node.js 12 actions. Updates to latest versions.
Also shorten CI job names to better see the actual job description
> Fix GHA warnings

- industrial_ci/src/tests/ros_prerelease.sh
closes #808 
@Nir-Az: Would you prefer that the jobs succeeds, but still prints the error?
> Notify that pre-release tests are not supported for EOL distros

- .github/workflows/main.yml
- doc/index.rst
There are a few `pylint` features in ICI but they are not set to be verified on CI of this repo so it's unclear whether it's working.
Add pipeline on this repo's CI.
> Improvement: [CI-self] Add jobs to verify pylint features

- .github/workflows/main.yml
Ubuntu-18.04 action runners have been removed
> Remove test for isolated melodic

- industrial_ci/src/ros.sh
This reverts commit 6931750a64c88d171e23b5397c6c14231acc27cd.
> Revert "Use building repo for rolling"

- .github/workflows/main.yml
- README.rst
- doc/industrial_ci_action.yml
> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> Migrate to actions/checkout@v4

- .github/workflows/main.yml
> This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
> Remove isolated tests for ubuntu-20.04

- industrial_ci/src/workspace.sh
This typo is ultimately inconsequential, but better fixed nonetheless
> Fix typo in ici_setup_gpg_key
