ros-industrial/industrial_ci

travis.sh
Perhaps `--no-notify` should be added as well.
=> Turn off status line

README.rst
Sorry for opening tiny PR pieces on and off...
=> [README] Add FAQ

travis.sh
With this #26 should disappear.
(This change isn't necessarily the permanent fix (discussion is ongoing in #26)).
=> Temporarilly disable rospack plugin line (fixes #26).

package.xml, travis.sh
Initialized by #30, with the Travis build of this PR I'm trying to find if there's any difference introduced by [catkin_tools 0.4.0 that was released today](http://lists.ros.org/pipermail/ros-users/2016-April/069968.html).
=> Adjust to catkin_tools 0.4.0

travis.sh
=> Remove wrong duplicate prerelease test code block.

.travis.yml, ros_pre-release.sh, travis.sh, util.sh
<s>**DO NOT Review nor Merge yet.**</s>
Ready to be reviewed.
=> Fix for #49 (prerelease test result failure)

.ci.rosinstall.jade, .travis.rosinstall, .travis.yml, README.rst, travis.sh
Just a rebased and squashed version of #47 that @rhaschke initiated.
=> Enable UPSTREAM_WORKSPACE option

README.rst
Fixes #29 
I think the scripts are good enough, everything works across several repositories.
=> Provide instructions for advanced_industrial_ci

.travis.yml, industrial_ci/ci_main.sh
=> Catch apt error for ADDITIONAL_DEB

industrial_ci/ci_main.sh, industrial_ci/ros_pre-release.sh, industrial_ci/rosdep-install.sh
=> comment shell options

industrial_ci/ci_main.sh
To be able to clone private repositories inside the docker container, the ssh agent needs to be forwarded into the docker container.
=> Support private github repositories on kinetic

industrial_ci/source_tests.sh
kinetic tests were run, but output was hidden.
=> attach docker container to stdout/err again

industrial_ci/src/ci_main.sh, industrial_ci/src/tests/source_tests.sh
Commits from  https://github.com/ipa-mdl/industrial_ci/pull/5 got lost while rebasing.
=> Minor before/after script clean-up

.travis.yml, industrial_ci/src/env.sh
=> support for ROS lunar

doc/index.rst
=> improved run_ci example

.travis.yml, doc/index.rst, industrial_ci/src/env.sh
as discussed in #132 
alias names are based on the server paths.
=> introduced ROS_REPO environment variable

.travis.yml, industrial_ci/src/tests/source_tests.sh, industrial_ci/src/util.sh
=> handle missing UPSTREAM_WORKSPACE file

doc/index.rst
as reported by @ipa-fxm
please rebase-merge
=> fixed syntax in example

industrial_ci/src/util.sh
When using industrial_ci with a CI service as Jenkins the output may be lost.
=> Changed urandom output for date hashing as it may cause problems with docker output.

.travis.yml
=> [enhance][doc?] Add a note for 'distro' attribute in .travis.yml

industrial_ci/CHANGELOG.rst
fixes #188 
In addition I fixed the spelling of my name ;)
=> fix changelog encoding

.gitlab-ci.yml
fixes #186 
@miguelprada: please review
=> [gitlab] use .ci_config again

.travis.yml
work-around for https://github.com/ros-infrastructure/rosdep/issues/532
=> downgrade rosdep to 0.11.5 in hydro test

.travis.yml
Reverts ros-industrial/industrial_ci#203
=> Revert "downgrade rosdep to 0.11.5 in hydro test"

.travis.yml
=> fix external test

industrial_ci/src/tests/source_tests.sh
=> print verbose catkin test results

industrial_ci/package.xml
Adding @miguelprada per consent.
Can any admin add him write access? Looks like I'm in @ros-industrial/ci-admins but don't have a right to do so.
=> Add a maintainer

.travis.yml, doc/index.rst, industrial_ci/src/env.sh
=> add support for ROS melodic

.travis.yml
=> test for debian stretch instead of jessie

README.rst, bitbucket.sh
This PR adds support for [BitBucket Pipelines](https://confluence.atlassian.com/bitbucket/get-started-with-bitbucket-pipelines-792298921.html).
=> add support for bitbucket-pipelines

industrial_ci/src/tests/clang_format_check.sh
This should skip hidden directories in the target path.
@wxmerkt: please test
=> fix clang format check crawl

.travis.yml, doc/index.rst, industrial_ci/src/docker.sh, industrial_ci/src/env.sh
=> Try to read ROS_DISTRO from docker images

travis.sh
Reverts ros-industrial/industrial_ci#365
=> Revert "use host network for travis"

.travis.yml, industrial_ci/src/docker.sh, industrial_ci/src/env.sh, industrial_ci/src/tests/abi_check.sh, industrial_ci/src/tests/ros_prerelease.sh, industrial_ci/src/tests/source_tests.sh
supersedes #372, supersedes #370  
~~Not sure if the logic is correct, https://github.com/osrf/docker_images/pull/269 will clarify this..~~
=> Key change and snapshots.ros.org support

industrial_ci/src/docker.sh
=> install dirmngr explicitly

industrial_ci/scripts/rerun_ci, industrial_ci/src/docker.sh, industrial_ci/src/tests/abi_check.sh, industrial_ci/src/tests/source_tests.sh, industrial_ci/src/util.sh
Especially SC2206, SC2207, SC2216
This fix now evaluates all arrays.
closes #385
=> fix new shellcheck errors

doc/index.rst, industrial_ci/src/env.sh, industrial_ci/src/tests/ros_prerelease.sh
This reverts commits ae0474fb5169489042460328b89eef004f3b0a0f and d56e1dc1f9fa32c1d5ef7dfdae529dcbec2eb4ce.
In addition, I updated the EOL status of lunar in the documentation.
=> Use final snaptshots for indigo and lunar

README.rst
Related to https://github.com/ros-industrial/ros_industrial_issues/issues/57
=> readme: added license badge

industrial_ci/src/env.sh
=> Revert revert revert using snapshots

industrial_ci/src/tests/ros_prerelease.sh
=> prepare dummy ~/.ccache directory in prerelease test

industrial_ci/scripts/run_travis
=> pass PATH in run_travis [legay]

.travis.yml, industrial_ci/src/tests/abi_check.sh, industrial_ci/src/util.sh, industrial_ci/src/workspace.sh
should fix #416 
rosenv was executed in a subshell, so `rosenv && ...` did not work.
=> Fix rosenv

README.rst
=> readme: repository was migrated to travis.com [master]

.travis.yml
=> test motoman_experimental against main ROS repository

industrial_ci/src/env.sh
needs ~~https://github.com/osrf/docker_images/pull/329~~ ~~https://github.com/docker-library/official-images/pull/7039~~
=> use default image for eloquent

industrial_ci/src/tests/abi_check.sh, industrial_ci/src/tests/ros_prerelease.sh
enable ccache for pre-release and ABI checks.
=> more ccache support

.github/action.js, .github/workflows/main.yml, README.rst, action.yml, doc/index.rst
addresses #343 
Example: https://github.com/ros-industrial/ros_canopen/blob/github-action/.github/workflows/main.yml
@gavanderhoorn, @agutenkunst: please test
=> added GitHub action and workflow

industrial_ci/src/tests/source_tests.sh
=> install catkin_lint from ROS repository [legacy]

.gitlab-ci.yml, .travis.yml, doc/index.rst, doc/migration_guide.md, industrial_ci/src/docker.sh, industrial_ci/src/env.sh
=> remove support for INJECT_QEMU

industrial_ci/scripts/run_travis
fixes https://github.com/ros-industrial/industrial_ci/issues/465
=> add HOME to whitelist

.travis.yml
Failing test will be resolved by https://github.com/ros-controls/ros_control/pull/415
=> switch from indigo to kinetic for most tests

industrial_ci/src/workspace.sh
to take advantage of https://github.com/ros-infrastructure/rosdep/pull/738
=> explicitly set ROS_DISTRO in rosdep update

.travis.yml, industrial_ci/scripts/run_travis
fixes #417 
I am not 100% sure about the regex..
@agutenkunst: please test
=> filter travis yaml like travis-build

industrial_ci/src/builders/catkin_make.sh, industrial_ci/src/builders/catkin_make_isolated.sh, industrial_ci/src/builders/catkin_tools.sh, industrial_ci/src/builders/colcon.sh
#446 did not enable non-parallel tests by default
Either the documentation or the code has to be fixed.
@fmessmer: FYI
=> fix handling of PARALLEL_TESTS

doc/index.rst
Document some things discovered in #376
=> Documentation for gitlab with self-signed certs

.travis.yml, industrial_ci/src/env.sh
* previous behavior is kept as ROS_REPO=ros1
=> make ROS_REPO=ros behave like ROS_REPO=main

doc/index.rst, industrial_ci/src/env.sh
=> switch ROS2 foxy from nightly build to testing

doc/.travis.yml, doc/index.rst, doc/migration_guide.md, industrial_ci/src/env.sh
=> handle ROS_REPO=ros-shadow-fixed for ROS2

industrial_ci/src/util.sh
Signed-off-by: Chen Bainian <brian97cbn@gmail.com>
Fix Shellcheck error in Github Action
=> Fix Shellcheck error

README.rst
As per subject.
It's supported since #499.
=> readme: mention noetic

.gitlab-ci.yml, doc/index.rst
Signed-off-by: Chen Bainian <brian97cbn@gmail.com>
Add instruction based on findings documented in #536
=> Add additional note on setting up ccache in Gitlab

.travis.yml
follow-up of https://github.com/ros-industrial/industrial_ci/pull/540#issuecomment-654172619
=> remove shellcheck from Travis CI and clean-up a bit

travis.sh
something went wrong with the merge of #543
=> Update libseccomp to fix statx syscall error

.ci.rosinstall.kinetic
=> pin actionlib version for kinetic test

industrial_ci/src/util.sh, industrial_ci/src/workspace.sh
=> improve error handling and reporting of ici_import_repository

industrial_ci/src/workspace.sh
in script only, not in Dockerfile
=> export DEBIAN_FRONTEND=noninteractive

industrial_ci/scripts/rerun_ci, industrial_ci/src/docker.sh
=> only commit credentials if DOCKER_COMMIT_CREDENTIALS=true

.github/workflows/external.yml, .github/workflows/main.yml, industrial_ci/_wrap_test.sh
Port tests from Travis to Github Actions
=> Port travis test cases to github actions

industrial_ci/src/tests/abi_check.sh, industrial_ci/src/tests/black_check.sh, industrial_ci/src/tests/ros_prerelease.sh, industrial_ci/src/util.sh, industrial_ci/src/workspace.sh
Fixes regression of #558 
Taken from #572
=> Fix permissions in setup_ros_prerelease and ici_init_apt

doc/index.rst, industrial_ci/src/util.sh
As reported in https://github.com/ros-industrial/industrial_ci/pull/572#issuecomment-761718057
=> Deal with unset variables in EMBED scrips

industrial_ci/src/builders/catkin_tools.sh
regression of #526
@ipa-lth: Thanks for reporting!
=> Bring back VERBOSE_TESTS

industrial_ci/src/isolation/docker.sh, industrial_ci/src/isolation/shell.sh, industrial_ci/src/tests/ros_prerelease.sh
* `ici_forward_mount` to setup mount from variable or file name. ensures that path is absolute (@gavanderhoorn: FYI)
* `ici_forward_variable` passes variables down to the isolated environment
=> Refactor handling of docker settings

.gitlab-ci.yml, industrial_ci/src/isolation/docker.sh
Fix BASEDIR issue with Docker (https://github.com/ros-industrial/industrial_ci/issues/578#issuecomment-767451862)
Test case (failing): https://gitlab.com/ipa-mdl/industrial_ci/-/jobs/989291921
Fix (passing): https://gitlab.com/ipa-mdl/industrial_ci/-/jobs/989415411
=> Copy target repo if BASEDIR is set

doc/index.rst, industrial_ci/_wrap_test.sh, industrial_ci/src/workspace.sh
=> Remove support for pip-style repository URLs

.travis.yml, README.rst
#600 and #601 for legacy branch
=> Point Travis CI badge to IPA mirror and reduce tests

.github/workflows/legacy.yml, industrial_ci/src/tests/source_tests.sh, industrial_ci/src/util.sh
=> Add Github Actions workflow

industrial_ci/src/tests/source_tests.sh
fixes https://github.com/ros-industrial/industrial_ci/issues/620
=> pylint handle no files

industrial_ci/src/util.sh, industrial_ci/src/workspace.sh
Fixes #624
@fmessmer: please test
=> (Re)populate ROS_PACKAGE_PATH from all underlays

README.rst
Based on the discussion from #635
=> Add quickstart example for Google Cloud Build

action.yml
Fixes #639 and helps with #638
=> Use GITHUB_ACTION_PATH instead of github.action_path

doc/index.rst
Monospace text uses two backticks.
=> Fixed some typos and wrong backticks

industrial_ci/src/ci_main.sh, industrial_ci/src/isolation/docker.sh, industrial_ci/src/util.sh, industrial_ci/src/workspace.sh
reverts #595 and #626
fixes #661
Gitlab: https://gitlab.com/ipa-mdl/industrial_ci/-/pipelines/290145549
=> Skip BASEDIR, CCACHE_DIR and industrial_ci in ici_import_directory

industrial_ci/src/workspace.sh
=> Fix ROS key detection on indigo

industrial_ci/src/docker.sh, industrial_ci/src/env.sh
Reverts ros-industrial/industrial_ci#685
=> Revert "Use default APTKEY_STORE_HTTPS instead of HASHKEY_SKS"

.github/action.sh, .github/workflows/main.yml, industrial_ci/src/builders/catkin_make_isolated.sh
=> Minor fixes for catkin_make_isolated

industrial_ci/src/builders/catkin_tools_isolated_devel.sh
Middle ground between #700  and #702
=> Add support for BUILDER=catkin_tools_isolated_devel

industrial_ci/src/workspace.sh
=> Do not report if /etc/apt/sources.list.d/ is empty

industrial_ci/src/util.sh, industrial_ci/src/workspace.sh
Same as in legacy branch.
Should work with rosdep as well.
=> Use debconf instead of DEBIAN_FRONTEND

industrial_ci/src/workspace.sh
=> Check if setup.bash exists in ici_source_setup

industrial_ci/src/builders/catkin_tools_isolated.sh
=> Do not isolate installs in catkin_tools_isolated

industrial_ci/src/builders/catkin_make_isolated_devel.sh
=> Fix job options passing in catkin_make_isolated_devel

industrial_ci/src/run.sh, industrial_ci/src/tests/abi_check.sh, industrial_ci/src/util.sh, industrial_ci/src/workspace.sh
Exit directly in various places, but close the fold only at the top level shell.
This is what errexit would do anyway, but it might be turned off in several places.
=> Fix exit handling

industrial_ci/src/workspace.sh
=> Setup ROS_REPOSITORY_PATH only if ROS_DISTRO is set

.github/workflows/main.yml
=> Run isolated pre-release test with control_msgs

industrial_ci/scripts/rerun_ci, industrial_ci/scripts/run_ci, industrial_ci/src/util.sh, industrial_ci/src/workspace.sh
=> Fix shellcheck issues

industrial_ci/src/folding/github_actions.sh, industrial_ci/src/isolation/docker.sh
set-output is deprecated
closes #792
=> Migrate GitHub action to Environment file

README.rst
I know, it's only one letter, but why not to fix it ;)
=> typo in main README.md

.gitlab-ci.yml
Before: https://gitlab.com/mathias-luedtke/industrial_ci/-/pipelines/769340193
After: https://gitlab.com/mathias-luedtke/industrial_ci/-/pipelines/769908962
=> Use newer version of dind

action.yml
fixes https://github.com/ros-industrial/industrial_ci/pull/847
=>  Use node20 for GitHub Action

industrial_ci/src/util.sh, industrial_ci/src/workspace.sh
Fixes #853 
@fmauch: This should do the trick, but I would rather fix it in a cleaner way (tomorrow?)..
=> Ensure that builder_test_results is exposed as an output

industrial_ci/src/tests/source_tests.sh
=> Pin catkin_lint version for python2

doc/industrial_ci_action.yml
=> Update actions/cache@v2 -> v4

.github/workflows/main.yml, doc/index.rst, industrial_ci/src/ros.sh
I know, it might be a bit early given that there is no main repo and no documentation branch for kilted, but it would be nice to be able to run CI pipelines against kilted testing.
=> Add support for ROS Kilted Kaiju

.github/workflows/main.yml
Cherry-picked from https://github.com/ros-industrial/industrial_ci/pull/908
=> Remove noetic pre-release tests
